language: node_js
node_js:
  - "10"
before_script:
  - gem install sass
  - npm install -g grunt
  - npm install
script:
  - grunt
  - tar czf release.tar.gz _site

deploy:
  provider: releases
  api_key: "4fad2c55f955d6e87ba9b0c6bfaf0cfb3716bdc7"
  file: "release.tar.gz"
  skip_cleanup: true