exclude:
  - node_modules
  - scss
  - package.json
  - gruntfile.js
  - start.cmd
  - coffee


url: "https://eric-range.de"

markdown: kramdown

name: Eric Range
email: eric.range@live.de
location: Jena, Germany
job : IT System Engineer

vita:
  - company: Jenoptik SSC GmbH
    period: September 2016 - present
    job: IT System Engineer
  - company: Jenoptik SSC GmbH
    period: September 2014 - present
    job: Working Student
  - company: Evonik Industries AG
    period: October 2010 - September 2013
    job: Working Student

education:
  - name: Friedrich-Schiller-University Jena
    period: October 2013 - September 2016
    location: Jena, Germany
    studies: M.Sc. Business Informatics
  - name: Baden-Wuerttemberg Cooperative State University
    period: October 2010 - September 2013
    location: Mannheim, Germany
    studies: B.Sc. Business Informatics

honorificSuffix: M.Sc. Business Informatics
