npm install grunt-contrib-watch --save-dev
npm install grunt-contrib-sass --save-dev
npm install mysql --save-dev
npm install grunt-contrib-uglify --save-dev
npm install grunt-autoprefixer --save-dev
npm install grunt-contrib-cssmin --save-dev
npm install grunt-contrib-htmlmin --save-dev
npm install grunt-contrib-coffee --save-dev
npm install grunt-contrib-jshint --save-dev