exclude:
  - node_modules
  - scss
  - package.json
  - gruntfile.js
  - start.cmd
  - coffee

url: "https://eric-range.de" # the base hostname & protocol for your site
markdown: kramdown

name: Eric Range
email: eric.range@live.de
location: Jena, Germany
job : Fullstack Developer

skills:
  - Nginx
  - Apache
  - HTML5
  - NodeJS
  - ECMAScript6
  - UI
  - UX
  - MongoDB
  - Web Engineering
  - SharePoint

vita:
  - company: Jenoptik AG
    period: September 2014 - Present
    job: Student Trainee
  - company: Evonik Industries AG
    period: October 2010 - September 2013
    job: Dual Studies

education:
  - name: Friedrich-Schiller-Universität
    period: October 2013 - September 2016
    location: Jena, Germany
    studies: M.Sc. Business Informatics
  - name: Duale Hochschule Baden-Württemberg
    period: October 2010 - September 2013
    location: Mannheim, Germany
    studies: B.Sc. Business Informatics
  - name: Technische Universität Ilmenau
    period: October 2008 - September 2010
    location: Ilmenau, Germany
    studies: Pre-Studies Program

honorificSuffix: B.Sc. Business Informatics
